### ISSUE TITLE
REI search doesn't prevent moving

### ISSUE THREAD

**Issue by DadiBit** [PieKing1215/InvMove-Fabric#1]
While using the REI mod search widget the W, A, S, D keys are not prevented from being handled. Both mods handle the keypress. It happens both in singleplayer and in multiplayer.

InvMove: 
Fabric Loader: 0.10.8
Fabric API: 0.25.1+build.416
Minecraft: 1.16.4
REI: 5.8.7

**Comment by DadiBit** [comment]
Never mind, I thought it was fixed but I'm now playing with openjdk 11 and it seems like it bugged InvMove again...

**Comment by PieKing1215** [comment]
Added REI compat in [v0.1.0](https://github.com/PieKing1215/InvMove-Fabric/releases/tag/v0.1.0)
Could use some expanding in the future but it should be good enough for now
