### ISSUE TITLE
InvMove v0.1.0 - crash when creating world

### ISSUE THREAD

**Issue by TheButterbrotMan** [PieKing1215/InvMove-Fabric#10]
When i try to generate a world in my modpack (incl. InvMove), my games crashes after joining.

My Modpack: https://www.curseforge.com/minecraft/modpacks/deathdusk

https://bytebin.lucko.me/BEmYwWQ0f2

**Comment by PieKing1215** [comment]
That bytebin link doesn't work now, but this is probably a duplicate of #9, which is fixed in [v0.1.1](https://github.com/PieKing1215/InvMove-Fabric/releases/tag/v0.1.1).
Feel free to reopen if not
