### ISSUE TITLE
Sprinting stops when sprint key is released

### ISSUE THREAD

**Issue by hashalite** [PieKing1215/InvMove-Fabric#5]
**Describe the bug**
Releasing the sprint key causes you to stop sprinting.  Normally it would continue sprinting as long as the forward key is held.

**Version and Mod List**
InvMove: 1.17-0.0.1-r1
Fabric Loader: 0.11.6
Fabric API: 0.35.2+1.17
Minecraft: 1.17

**Comment by PieKing1215** [comment]
Should be fixed in [v0.1.0](https://github.com/PieKing1215/InvMove-Fabric/releases/tag/v0.1.0)
