### ISSUE TITLE
InvMove 0.1.0 - Unknown crash caused when joining a new world

### ISSUE THREAD

**Issue by Excaliburning** [PieKing1215/InvMove-Fabric#9]
Hello !

Sorry for not bringing much additional information besides the crash report.
I am not sure how to interpret this error, nothing is obvious to me in this crash log.
https://crashy.net/w1bQp3fbAOzqhKY3BgGu?raw

The most obvious culprit would have been Blur in my opinion, sadly, disabling it did not change the outcome.
https://crashy.net/YKAQ3g8YmsswC6n8k9CF?raw

If you need further information, I will happily oblige.
Running on W10, MC1.18.1, Fabric 0.12.12

**Comment by PieKing1215** [comment]
Thanks for the report!

Not sure what would cause this but it should be easy enough to fix.
I just need to change this assertion to a graceful check (not sure why I didn't do that in the first place)
https://github.com/PieKing1215/InvMove-Fabric/blob/4aebbe6d3fa47dad6caed03de7ce4e682e05e95b/src/main/java/me/pieking1215/invmove/InvMove.java#L312

**Comment by Excaliburning** [comment]
I was writting a bug report for Krypton as well when writing this, and mislabled the title. Thanks for taking note of this issue!

**Comment by TheButterbrotMan** [comment]
Greetings, i have an similar bug, when generating my world. Probably any mod incompatible, caused i have included InvMove in my Modpack.

**Comment by PieKing1215** [comment]
Should be fixed in [v0.1.1](https://github.com/PieKing1215/InvMove-Fabric/releases/tag/v0.1.1)
